using System.Collections.Concurrent;
using Tuxflix.Player;
using Xunit;

namespace Tuxflix.Tests;

/// <summary>
/// The libmpv binding driving real playback, silently: no video output, no audio output, and a
/// test pattern generated by ffmpeg's own filters instead of a file.
/// </summary>
public sealed class PlayerTests
{
    private static MpvPlayer Silent() => new(new Dictionary<string, string>
    {
        ["vo"] = "null",
        ["ao"] = "null",
        ["audio"] = "no",
        ["idle"] = "yes",
        ["config"] = "no",
        ["terminal"] = "no",
    });

    [Fact]
    public async Task APatternLoadsPlaysThroughAndFinishes()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var loaded = new TaskCompletionSource();
        var ended = new TaskCompletionSource<EndReason>();
        var positions = new ConcurrentBag<double>();
        player.FileLoaded += () => loaded.TrySetResult();
        player.Ended += (reason, _) => ended.TrySetResult(reason);
        player.Changed += change =>
        {
            if (change is { Name: "time-pos", Number: { } seconds }) positions.Add(seconds);
        };

        player.Load("av://lavfi:testsrc2=duration=1.5:size=320x180:rate=30");

        await loaded.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        var reason = await ended.Task.WaitAsync(TimeSpan.FromSeconds(15), TestContext.Current.CancellationToken);

        Assert.Equal(EndReason.Finished, reason);
        Assert.True(positions.Count >= 5, $"only {positions.Count} positions were reported");
        Assert.True(positions.Max() >= 1.0, $"playback stopped at {positions.Max():0.00} s");
    }

    [Fact]
    public async Task ACommandMpvRefusesRunsItsFallbackAndOneItTakesDoesNot()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        // Audio this time, to a null device that takes it in real time, so a filter graph runs.
        using var player = new MpvPlayer(new Dictionary<string, string>
        {
            ["vo"] = "null",
            ["ao"] = "null",
            ["idle"] = "yes",
            ["config"] = "no",
            ["terminal"] = "no",
        });
        var loaded = new TaskCompletionSource();
        player.FileLoaded += () => loaded.TrySetResult();
        player.Load("av://lavfi:sine=frequency=440:duration=60");
        await loaded.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);

        // No filter carries this label: refused, and the fallback runs.
        var refused = new TaskCompletionSource();
        player.PostCommand(() => refused.TrySetResult(), "af-command", "nowhere", "g", "3", "equalizer@b0");
        await refused.Task.WaitAsync(TimeSpan.FromSeconds(5), TestContext.Current.CancellationToken);

        // A labelled chain that audio has flowed through takes the command: no fallback. mpv answers
        // in order, so a second, refused command marks when the first has been answered.
        player.PostProperty("af", "@fx:lavfi=[equalizer@b0=f=60:t=q:w=1.1:g=0]");
        await Task.Delay(TimeSpan.FromSeconds(1), TestContext.Current.CancellationToken);
        var fellBack = false;
        var answered = new TaskCompletionSource();
        player.PostCommand(() => fellBack = true, "af-command", "fx", "g", "3", "equalizer@b0");
        player.PostCommand(() => answered.TrySetResult(), "af-command", "nowhere", "g", "3", "equalizer@b0");
        await answered.Task.WaitAsync(TimeSpan.FromSeconds(5), TestContext.Current.CancellationToken);

        Assert.False(fellBack, "mpv refused a command for a filter it has");
    }

    [Fact]
    public async Task ASourceThatCannotOpenEndsAsAFailure()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var ended = new TaskCompletionSource<(EndReason Reason, string? Error)>();
        player.Ended += (reason, error) => ended.TrySetResult((reason, error));

        player.Load("/no/such/file.mkv");

        var (reason, error) = await ended.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        Assert.Equal(EndReason.Failed, reason);
        Assert.False(string.IsNullOrEmpty(error));
    }

    [Fact]
    public async Task ResumingStartsWhereAskedRatherThanAtTheBeginning()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var first = new TaskCompletionSource<double>();
        player.Changed += change =>
        {
            if (change is { Name: "time-pos", Number: { } seconds }) first.TrySetResult(seconds);
        };

        player.Load("av://lavfi:testsrc2=duration=20:size=320x180:rate=30", start: 12);

        var position = await first.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        Assert.InRange(position, 11.5, 13.5);
    }
}
