using System.Collections.Concurrent;
using Tuxflix.Player;
using Xunit;

namespace Tuxflix.Tests;

/// <summary>
/// The libmpv binding driving real playback, silently: no video output, no audio output, and a
/// test pattern generated by ffmpeg's own filters instead of a file.
/// </summary>
public sealed class PlayerTests
{
    private static MpvPlayer Silent() => new(new Dictionary<string, string>
    {
        ["vo"] = "null",
        ["ao"] = "null",
        ["audio"] = "no",
        ["idle"] = "yes",
        ["config"] = "no",
        ["terminal"] = "no",
    });

    [Fact]
    public async Task APatternLoadsPlaysThroughAndFinishes()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var loaded = new TaskCompletionSource();
        var ended = new TaskCompletionSource<EndReason>();
        var positions = new ConcurrentBag<double>();
        player.FileLoaded += () => loaded.TrySetResult();
        player.Ended += (reason, _) => ended.TrySetResult(reason);
        player.Changed += change =>
        {
            if (change is { Name: "time-pos", Number: { } seconds }) positions.Add(seconds);
        };

        player.Load("av://lavfi:testsrc2=duration=1.5:size=320x180:rate=30");

        await loaded.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        var reason = await ended.Task.WaitAsync(TimeSpan.FromSeconds(15), TestContext.Current.CancellationToken);

        Assert.Equal(EndReason.Finished, reason);
        Assert.True(positions.Count >= 5, $"only {positions.Count} positions were reported");
        Assert.True(positions.Max() >= 1.0, $"playback stopped at {positions.Max():0.00} s");
    }

    [Fact]
    public async Task ASourceThatCannotOpenEndsAsAFailure()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var ended = new TaskCompletionSource<(EndReason Reason, string? Error)>();
        player.Ended += (reason, error) => ended.TrySetResult((reason, error));

        player.Load("/no/such/file.mkv");

        var (reason, error) = await ended.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        Assert.Equal(EndReason.Failed, reason);
        Assert.False(string.IsNullOrEmpty(error));
    }

    [Fact]
    public async Task ResumingStartsWhereAskedRatherThanAtTheBeginning()
    {
        if (!MpvPlayer.IsAvailable) Assert.Skip("libmpv is not installed here.");

        using var player = Silent();
        var first = new TaskCompletionSource<double>();
        player.Changed += change =>
        {
            if (change is { Name: "time-pos", Number: { } seconds }) first.TrySetResult(seconds);
        };

        player.Load("av://lavfi:testsrc2=duration=20:size=320x180:rate=30", start: 12);

        var position = await first.Task.WaitAsync(TimeSpan.FromSeconds(10), TestContext.Current.CancellationToken);
        Assert.InRange(position, 11.5, 13.5);
    }
}
