// Generates src/Tuxflix.App/Themes/Icons.axaml from the Phosphor icon set (MIT, see NOTICES.txt).
//
// Every icon is one filled path on a 256-unit grid, which is exactly what a StreamGeometry
// holds, so the icons theme through Foreground like text does and stay crisp at any size.
// The source is pinned to a commit so a regeneration never changes an icon nobody asked for.
//
//   node tools/gen-icons.mjs
//
// Keys are "Icon.<Name>" for the regular weight and "Icon.<Name>.<Weight>" for the others.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const COMMIT = "2b75f3ad12b420c9504ef05df8d2564a28f8500e";
const BASE = `https://raw.githubusercontent.com/phosphor-icons/core/${COMMIT}/assets`;

const ICONS = {
  regular: [
    "house", "squares-four", "rows", "caret-left", "caret-right", "caret-down", "caret-up",
    "arrow-left", "arrow-right", "magnifying-glass", "funnel-simple", "sliders-horizontal",
    "download-simple", "bell", "user-circle", "minus", "square", "copy", "x", "check",
    "check-circle", "eye", "eye-slash", "dots-three", "info", "star", "list-plus",
    "bookmark-simple", "film-strip", "television-simple", "music-notes", "image",
    "folder-simple", "clock", "calendar-blank", "gear", "sign-out", "hard-drives", "globe",
    "cloud", "plus", "arrows-clockwise", "speaker-high", "speaker-slash", "subtitles",
    "corners-out", "corners-in", "picture-in-picture", "skip-forward", "skip-back",
    "shuffle", "repeat", "queue", "pulse", "chart-bar", "sort-ascending", "keyboard",
    "game-controller", "warning", "warning-circle", "play-circle", "film-slate", "users",
    "user", "clock-counter-clockwise", "x-circle", "wifi-high", "lightning", "lock-simple",
    "link-simple", "sparkle", "compass", "list", "sidebar-simple",
  ],
  fill: [
    "house", "play", "pause", "star", "check-circle", "bookmark-simple", "circle",
    "television-simple", "film-strip", "music-notes", "image", "folder-simple",
    "speaker-high", "skip-forward", "skip-back", "play-circle", "users", "lightning",
    "warning", "info", "compass", "pulse", "user-circle",
  ],
  bold: [
    "arrow-left", "arrow-right", "caret-left", "caret-right", "caret-down", "caret-up", "x",
    "check", "magnifying-glass", "minus", "plus", "square", "copy",
  ],
};

const pascal = (name) =>
  name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");

async function fetchPaths(weight, name) {
  const file = weight === "regular" ? `${name}.svg` : `${name}-${weight}.svg`;
  const response = await fetch(`${BASE}/${weight}/${file}`);
  if (!response.ok) throw new Error(`${weight}/${file}: HTTP ${response.status}`);
  const svg = await response.text();
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (paths.length === 0) throw new Error(`${weight}/${file}: no path data`);
  if (/<(circle|rect|line|polyline|polygon|ellipse)\b/.test(svg)) {
    throw new Error(`${weight}/${file}: has shapes other than paths`);
  }
  return paths.join(" ");
}

const entries = [];
const failures = [];
for (const [weight, names] of Object.entries(ICONS)) {
  for (const name of names) {
    try {
      const data = await fetchPaths(weight, name);
      const key = weight === "regular" ? `Icon.${pascal(name)}` : `Icon.${pascal(name)}.${pascal(weight)}`;
      entries.push(`    <StreamGeometry x:Key="${key}">${data}</StreamGeometry>`);
    } catch (error) {
      failures.push(error.message);
    }
  }
}

if (failures.length > 0) {
  console.error(failures.join("\n"));
  process.exit(1);
}

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "Tuxflix.App", "Themes", "Icons.axaml");
const header = `<!-- Generated by tools/gen-icons.mjs from Phosphor Icons (MIT) at ${COMMIT.slice(0, 12)}. Do not edit by hand. -->`;
writeFileSync(
  target,
  `${header}\n<ResourceDictionary xmlns="https://github.com/avaloniaui"\n                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">\n${entries.join("\n")}\n</ResourceDictionary>\n`,
);
console.log(`Wrote ${entries.length} icons to ${target}`);
